### ISSUE TITLE
Speed rewrite changes

### ISSUE THREAD

**Issue by legoboyvdlp** [legoboyvdlp/A320-family#113]
Functional errors found during review:

- the format of the latitude / longitude on INIT A I believe to be wrong - it should be as such:
![image](https://user-images.githubusercontent.com/10434911/79114907-64df6480-7d7c-11ea-9287-33c21c038424.png)

I have code to translate to that format already. 
- after the IRS INIT prompt disappears you can still spawn the IRS page from INIT A by clicking button L3.
- the route selection page shouldn't spawn unless you have company routes available:
![image](https://user-images.githubusercontent.com/10434911/79114821-2cd82180-7d7c-11ea-9442-6c0d07a17397.png)

In terms of company routes there is a good nasal.io framework for inputing files, maybe that could be useful to look into later.

- cruise altitude input on INITA requires temperature - if no temperature is specified, it should default to ISA temperature for the altitude:
![image](https://user-images.githubusercontent.com/10434911/79115136-f8b13080-7d7c-11ea-9afb-b50debd64539.png)

- it should be possible to enter only temperature by inputing for instance "/-24". 

- PERF TO page should support separate input of THS and flap as such: "/UP0.6" or "2"
- PERF TO runway should be populated from FMGC.
- What are the conditions you made for switching between PERF phases? I need to check those, if you use the ones I made like three years ago they weren't great! 🤣 

- managed speed commands VLS on approach - with flap 1, surely it should command S speed?

Very minor, unimportant things:
- PERF TO page can support UP0.6 or 0.6UP
- on INITB, final / time should really default to "---.- / 0030". 
- PERF APPR wind, it shows

**Comment by merspieler** [comment]
> it should be possible to enter only temperature by inputing for instance "/-24".

Actually this is a thing that applies to almost all dual value (`/` seperated) fields that just entering something without the / sets the first field and `/<value>` sets the second.

**Comment by legoboyvdlp** [comment]
yep 👍

**Comment by mattmaring** [comment]
Cool, I wanted to focus on breaking changes before updating the entry formats. I'll go through and correct all of those (I've got a list going, there are others as well).

- Lat/Lon needs updated on IRS INIT as well (tho that one is a different format), I'd definitely appreciate using code you already have :)
- As for company routes, my plan is eventually to have a database file for the other default values, so that could definitely be something in the future. Are you saying it doesn't spawn if you don't have any company routes (not just for that particular route)?
- Conditions for PERF phases still need improvements. I didn't touch most of the logic, the only thing I should have changed are:
    - added the ability to manually trigger approach/decel with PERF pages
    - added a transition to done (so pfd stuff would go away)
    - ability to cancel approach selection or continue go-around with PROG page
- "on INITB, final / time should really default to "---.- / 0030"", yep! I needed the FPLN or that was impossible to do :)
- "managed speed commands VLS on approach - with flap 1, surely it should command S speed?", see PRO-SUP-10:
<img width="609" alt="Screen Shot 2020-04-13 at 8 20 41 AM" src="https://user-images.githubusercontent.com/56924612/79119978-ac0b2c80-7d5f-11ea-9a5a-a540ea1e27af.png">

What do you mean by:
- PERF TO runway should be populated from FMGC.
- PERF APPR wind, it shows

**Comment by mattmaring** [comment]
Additional list of things for myself to fix:
- Hide speed protection bars before ILS aligned
- VLS adjustment for height
- Add big/small text adjustments to mcdu

(FPLN integration - might be done here or later on another brach, depending on how long the above bug fixes take)

**Comment by legoboyvdlp** [comment]
PERF TO runway should be the selected departure runway in the DEPARTURE page of the MCDU. I can do that shortly. 

PERF APPR wind, sorry, I didn't finish writing!

I entered 060/24 and got 60/4 - I am unsure if that is correct - does it trim off the leading zero?

In terms of managed speed, the FMGC was commanding VAPP speed. However, with flaps zero, that was into the speed protection bars!

**Comment by legoboyvdlp** [comment]
> I'd definitely appreciate using code you already have :)

I think I have some on LATREV page?

**Comment by mattmaring** [comment]
That's odd, I tried entering 060/24 and it worked just fine. It will accept any wind value, but it does trim (5, 15) in the calcs.
<img width="343" alt="Screen Shot 2020-04-13 at 8 53 36 AM" src="https://user-images.githubusercontent.com/56924612/79121836-44a3ab80-7d64-11ea-8177-5b897126be9a.png">

For managed speed, it should display VAPP as the target, but will fly the VLS for that flap config. This video shows it pretty well:
https://www.youtube.com/watch?v=9VfI4Pyam1E

Cool, I'll look there tonight.

**Comment by legoboyvdlp** [comment]
Ok - that's great!

**Comment by legoboyvdlp** [comment]
For the runway:
if fmgc.flightPlanController.flightplans[2].departure_runway != nil, setText to the value stored in fmgc.flightPlanController.flightplans[2].departure_runway.id 


that will add info to field R1 on the PERF TO page

**Comment by mattmaring** [comment]
All are fixed on mcdu branch

**Comment by legoboyvdlp** [comment]
Great, thanks. :)
