### ISSUE TITLE
Bug - Replay system broken?

### ISSUE THREAD

**Issue by vezza** [legoboyvdlp/A320-family#124]
**Describe the bug**
1) The replay system doesn't replay some properties (example: airspeed, clock/timers, brake decel indicator, brake fan, brake hot indicator, and probably many more...).
2) Exiting the replay the panel state gets reset to cold and dark

**To Reproduce**
1. do a quick flight;
2. enter the replay system (CTRL+R);
3. check for missing data/properties;
4. exit the replay;
5. see the cockpit reset to cold and dark state 

**Expected behavior**
I would expect the replay showing correct property value's and that exiting the replay, properties gets resets to the pre-replay's values

**Screenshots**

** System (please complete the following information):**
 - OS: Linux (Fedora 31 x86_64)
 - FlightGear version: 2019.2.0 (dev branch)

**Additional context**

**Comment by Octal450** [comment]
The behavior is intentional.
Replay fucks up many of the systems and FMGC logic, as it thinks its actually flying. So we purposefully reset after ending. This even happens in PMDG planes in P3D, if you use slew/replay, some stuff will be weird/screwed up after exiting.

As for missing properties, you can add those yourself to flight-recorder.xml, or tell me the properties needed and I will add them

Kind Regards,
Josh

**Comment by vezza** [comment]
Ok thanks, anyway I think this issue should remain open on a low priority... there should be a way to save the sim state before replay and reopen it after leaving the replay (example: a function that creates a copy of the property tree before the replay and then restores it leaving the replay). What do you think?

**Comment by Octal450** [comment]
Not really possible.
That state system doesn't know or care about the value of things - that would be saving thousands and thousands of properties.
It just resets everything to as if the sim just loaded, then starts the plane to the selected state.

Kind Regards,
Josh
