### ISSUE TITLE
FlightGear doesn't start when using this aircraft

### ISSUE THREAD

**Issue by wrongsyntax** [legoboyvdlp/A320-family#173]
When trying to load up the A320, an error appears on the loading screen, not letting me use the aircraft.
### General
----

I am submitting a: (select one) 
* [x] Bug report
* [ ] Feature request

### Details
----
#### Expected Behavior (bug reports)

The aircraft should load up and I should be able to use it.
#### Current Behavior (if applicable)

![Error that shows up](https://user-images.githubusercontent.com/29494694/88970915-66bc2d80-d270-11ea-989c-06ef472348df.png)

#### Steps to Reproduce (bug reports)

1. Select the A320
2. Click Fly
3. See error

**Comment by legoboyvdlp** [comment]
I wonder what that file called "INSTALL.MD" is for. It certainly isn't for reading, if a user has difficulty installing and using, or at least, nobody ever seems to read it...


Anyway, this is caused by not removing the extension which Github adds to the .zip file -- rename the folder to `A320-family`.

**Comment by wrongsyntax** [comment]
Oh sorry, I didn't see that. Maybe it might be a good idea to at least reference it in the README, since that's pretty visible on the home page?

**Comment by legoboyvdlp** [comment]
No problem, and yes, that would be good :+1: 🙂
