### ISSUE TITLE
Bug - Aileron movement without ELAC and SEC

### ISSUE THREAD

**Issue by merspieler** [legoboyvdlp/A320-family#180]
**Describe the bug**

When ELACs and SECs are turned off, there are no computers controlling the ailerons so they shouldn't move.

**To Reproduce**
1. Turn ELAC 1 and 2 as well as SEC 1, 2 and 3 off
2. Move ailerons on when on ground, extend flaps when in air
3. note that the Ailerons move/droop

**Expected behaviour**
No aileron movement since computers are off

**Comment by Octal450** [comment]
I'll sort this in the FDM rework, have to update the FCS/FBW a bit anyways and possibly in the dev too, I'll investigate.

Josh

**Comment by legoboyvdlp** [comment]
fwiw I already did all the fcs changes I sent to you in discord ;)

**Comment by Octal450** [comment]
👍

**Comment by legoboyvdlp** [comment]
Is it just me or can the pitch trim move without HYD?

**Comment by Octal450** [comment]
You can move the wheel. Isn't there mech backup for trim?

**Comment by merspieler** [comment]
afaik, the MECH backup law covers yaw via rudder and pitch via the THS

**Comment by legoboyvdlp** [comment]
@merspieler sorry, we discussed this privately and came to the conclusion, I forgot to post it here,

Basically the manual input goes to the input shaft which controls the hydraulic actuator; the actuator still needs hydraulic pressure, otherwise it can't move (it is locked in place if it loses pressure).

So basically its mechanical input to the hydraulic actuator if the electronic input fails. It doesn't actually mechanically go to the screwjack; you need hydraulics for the actuator to work.

**Comment by merspieler** [comment]
okay... didn't knew that...

**Comment by Octal450** [comment]
Will be checked out
