### ISSUE TITLE
Bug - FlightPlan Reset

### ISSUE THREAD

**Issue by AAL5665** [legoboyvdlp/A320-family#236]
**Describe the bug**
When the PERF or INiTI Page is pressed during flight it resets the flightplan clearing everything

**Expected behaviour**
When press should only open the page and not reset the flightplan

**System (please complete the following information):**
 - OS: MacOS
 - FlightGear version: FlightGear 2020.3.8

**Comment by legoboyvdlp** [comment]
Please give more detailed instructions to reproduce (as detailed as possible). I suspect you are doing something wrong, because that should only ever occur  if your internal FMGC phase is = 7. This only occurs 30 seconds after landing. Are you for instance, landing at an airport, and then taking off again multiple times?

**Comment by AAL5665** [comment]
No

**Comment by AAL5665** [comment]
I was at FL204 and a even increased the sim speed and made 3 headings with a flightplan in after takeoff so I don't that is a possibility

**Comment by legoboyvdlp** [comment]
Well, I need more information than that, sorry, to reproduce it.

**Comment by legoboyvdlp** [comment]
Information requested wasn't provided - can't reproduce - can't fix.
