### ISSUE TITLE
Bug - 

### ISSUE THREAD

**Issue by Devansh1007** [legoboyvdlp/A320-family#274]
Mass and balance file is missing in the 3D branch resulting in wrong CG value in fuel and payload section.

**Comment by Octal450** [comment]
No, that's not what's going on or what would happen with missing mass balance data. The mass model is now type specific so each specific type now has it's own mass balance model.

You should not take the readout in Fuel and Payload seriously, it's only a coordinate reference. Real value reference to MAC and other things is correct. If you suspect the model is wrong, please let me know how and I can reopen it.

Kind Regards,
Josh

**Comment by legoboyvdlp** [comment]
Mass and balance is not in fact missing, if it was missing the aircraft would not work. It's all contained within the JSBSim files.

The reason the coordinates do not match is because the FlightGear A320 uses an aircraft-centric coordinate frame with the origin in the middle of the aircraft, while the real A320 uses a reference frame where the origin is somewhere in front of the nose of the aircraft (from memory).

However, I do agree that we need a way to get the center of gravity position relative to the aircraft reference frame to enable people to calculate the takeoff trim appropriately. For reference, see the Weight and Balance manual which is available online. 


For the record, I verified that the center of gravity etc is all correct, except that it's operating in a different coordinate system.

**Comment by Devansh1007** [comment]
Thanks for the effort and response, guys. Yeah! Even I realised that mass and balance is present. Not as a dedicated file but in the each variant of the aircraft family. Everything is just right from the weight to metrics. I got the way to calculate CG for trim. I found that this time aircraft has been shifted on the coordinates. So, I am good with the trim calculation again. 

Thanks!
