### ISSUE TITLE
Bug - floodlights aren't working for me can you fix that in the a320

### ISSUE THREAD

**Issue by DANIElLOVEsPLANES** [legoboyvdlp/A320-family#321]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**System (please complete the following information):**
 - OS: 
 - FlightGear version: 
 - A320 Version: (FGAddon/Laucher or branch with commit)

**Additional context**

**Comment by linguisticmind** [comment]
Same here.

**Describe the bug**
Turning the FLOOD LT MAIN PLN and FLOOD LT PED knobs has no effect.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start up the aircraft
2. Turn the said knobs

**Expected behaviour**
Floodlights working.

**System (please complete the following information):**

 - OS: Debian Stable (12, Bookworm)
 - FlightGear version: 2020.3.19
 - A320 Version: dev, 8869ad8

---

The FLOOD LT PED knob is also misnamed as "FLOOD LT MAIN PLN". The FGAddon version says "FLOOD LT PED".

Current:

![fgfs-20240525021622](https://github.com/legoboyvdlp/A320-family/assets/54222750/1c746198-bcd4-45ad-b50a-ff1063cf982e)

FGAddon:

![fgfs-20240525020341](https://github.com/legoboyvdlp/A320-family/assets/54222750/ace40073-3637-4863-bcb5-9c021cb94f42)

**Comment by Octal450** [comment]
@DANIElLOVEsPLANES You didn't fill out the template. Why???

@linguisticmind I think the Git version requires compositor (2020.4) at the moment. I'll have to look getting dual support in before next FGAddon release.

**Comment by linguisticmind** [comment]
Confirmed to work on 2020.4.

In case someone else wonders about how to download the nightly version:

- FlightGear nightly: https://download.flightgear.org/builds/nightly/
- fgdata for nightly: https://gitlab.com/flightgear/fgdata (I installed it by running `git clone https://gitlab.com/flightgear/fgdata.git`)

**Comment by L1011H** [comment]
> The FLOOD LT PED knob is also misnamed as "FLOOD LT MAIN PLN". The FGAddon version says "FLOOD LT PED

If you are referring to the F/O side, this indeed was misnamed and is now fixed. Will be available with the next commit. Thanks

@linguisticmind

**Comment by Octal450** [comment]
Known. Won't be fixed. Next FGAddon release will be 2024.1.
Lights work in 2024.1.
